---
name: package

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    name: Export with Ruby
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v3
        with:
          ruby-version: "3.2"

      - name: Install gem dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Export files
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
          RUBYGEMS_API_KEY: "${{ secrets.RUBYGEMS_API_KEY }}"
          NPM_AUTH_TOKEN: "${{ secrets.NPM_AUTH_TOKEN }}"
        run: |
          ./bin/package
