---
name: package

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    name: Export with Ruby ${{ matrix.ruby }}
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7.x"]

    steps:
      - uses: actions/checkout@v2.4.0

      - uses: actions/cache@v2.1.7
        with:
          path: vendor/bundle
          key: >
            ${{ runner.os }}-${{ matrix.ruby }}-gems-${{
            hashFiles('**/*.gemspec') }}
          restore-keys: >
            ${{ runner.os }}-${{ matrix.ruby }}-gems-${{
            hashFiles('**/*.gemspec') }}

      - name: Set up Ruby
        uses: actions/setup-ruby@v1.1.3
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install gem dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Export files
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
          RUBYGEMS_API_KEY: "${{ secrets.RUBYGEMS_API_KEY }}"
          NPM_AUTH_TOKEN: "${{ secrets.NPM_AUTH_TOKEN }}"
        run: |
          ./bin/package
